# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection:
        enabled: true
    session:
        cookie_secure: false
        cookie_samesite: lax
        cookie_httponly: true
        cookie_domain: null
        cookie_lifetime: 0
        gc_maxlifetime: 1440


    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
