
services:
###> doctrine/doctrine-bundle ###
  database:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      - .env.local
###< doctrine/doctrine-bundle ###

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

###> symfony/mailer ##
  # mailer:
  #   image: axllent/mailpit
  #   ports:
  #     - "1025"
  #     - "8025"
  #   environment:
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
