controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_api_reordena:
    path: /api/reordena
    controller: App\Controller\TarefaController::alteraOrdemApresentacao
